name: 'Steampipe GitHub Action'
author: 'Turbot.com'
description: 'Set up a specific version of Steampipe'

branding:
  color: 'red'
  # TBD
  icon: 'code'

inputs:
  version:
    description: Version of Steampipe that will be installed.
    required: false
    default: latest
  plugins:
    description: A list of plugins to install and configure (comma-separated)
    required: true ## no point running steampipe without any plugins.
  connection_config:
    description: Connection config that steampipe will use.
    required: false
    default: ""
  run:
    description: A list of benchmarks and controls to run (comma-separated). If left blank, `all` controls and benchmarks are run.
    required: false
    default: ""
  mod:
    description: Git URL of a mod that will be installed. Will be passed on to `git clone`.
    required: true
  output:
    description: Select a console output format i.e. brief, csv, html, json, md, text or none
    required: false
    default: text
  export:
    description: "Export output to files in various output formats such as csv, html, json, md, nunit3 or asff (json) - comma separated"
    required: false
    default: ""
  where:
    description: SQL 'where' clause, or named query, used to filter controls
    required: false
    default: ""
  event_name:
    description: Name of the event that triggered the workflow
    required: false
    default: ${{ github.event_name }}
  github_token:
    description: The GITHUB_TOKEN of the user
    required: false
    default: ${{ github.token }}

runs:
  using: node16
  main: dist/index.js
