name: 'Steampipe GitHub Action'
author: 'Turbot.com'
description: 'Set up a specific version of Steampipe'

branding:
  color: 'red'
  # TBD
  icon: 'code'

inputs:
  version:
    description: Version of Steampipe that will be installed.
    required: false
    default: latest
  plugins:
    description: A list of plugins to install and configure (comma-separated)
    required: true ## no point running steampipe without any plugins.
  connection_config:
    description: Connection config that steampipe will be initialized with.
    required: true ## no point if the plugins are not configured
  control:
    description: List of controls to be executed. Will be passed on to `steampipe check`.
    required: false
  benchmark:
    description: List of benchmarks to be executed. Will be passed on to `steampipe check`.
    required: false
  mod:
    description: Git URL of a mod that will be installed. Will be passed on to `git clone`.
    required: true
  output:
    description: Select a console output format i.e. brief, csv, html, json, md, text or none
    required: false
    default: md
  export:
    description: "Export output to files in various output formats: csv, html, json, md, nunit3 or asff (json) - comma separated"
    required: false
    default: ""
  where:
    description: SQL 'where' clause, or named query, used to filter controls
    required: false
    default: ""

runs:
  using: node16
  main: dist/index.js
