---
name: Steampipe Check
author: Turbot
description: Run Steampipe mod controls and create annotations for Infrastructure as Code controls.
branding:
  color: red
  icon: shield
inputs:
  mod-url:
    description: "Mod URL to clone. Examples: https://github.com/turbot/steampipe-mod-aws-compliance"
    required: true
  mod-branch:
    description: 'Mod branch or tag to clone. Defaults to "main". Examples: main, release/v0.7, 0.5, 1.0.'
    required: false
    default: main
  checks:
    description: 'Space separated list of benchmarks and controls to run. Can also pass in as a multi-line string. Defaults to "all".'
    required: true
    default: all
  create-annotations:
    description: If true, create annotations in pull requests for controls that have a "path" additional dimension with the format `filename:linenumber`.
    required: false
    default: false
  additional-args:
    description: 'Space separated args to add to the "steampipe check" command.'
    required: false
  snapshot-type:
    description: If set to 'public' or 'private' will create a snapshot on Turbot Pipes *requires input 'pipes-token'*, other values or not being set will not.
    required: false
  pipes-token:
    description: The Turbot Pipes token used to save snapshots, required if 'snapshot-type' is set.
    required: false
  github-token:
    description: GitHub token used to push annotations and job summaries.
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Create temporary directories
      shell: bash
      id: make-temp-dir
      run: |
        # Create temporary directories for Steampipe and mod installation
        tmp=$(mktemp -d)
        tmp_mod_dir=$tmp/mod_dir
        mkdir -p $tmp_mod_dir
        echo "tmp-mod-dir=$tmp_mod_dir" >> $GITHUB_OUTPUT

    - name: Get mod
      shell: bash
      run: |
        # Clone and setup mod
        if [ -z "${{inputs.mod-branch}}" ]; then
          git clone --depth 1 "${{ inputs.mod-url }}" "${{ steps.make-temp-dir.outputs.tmp-mod-dir }}"
        else
          git clone --depth 1 -b "${{ inputs.mod-branch }}" --single-branch "${{ inputs.mod-url }}" "${{ steps.make-temp-dir.outputs.tmp-mod-dir }}"
        fi
        cd ${{ steps.make-temp-dir.outputs.tmp-mod-dir }}
        steampipe mod install
        cd -

    - name: Get checks
      id: get-checks
      shell: bash
      run: |
        # Convert multiline 'checks' input to single line arguments which we can send to 'check'
        if [ -z "${{ inputs.checks }}" ]
        then
          # default to all
          run_list="all"
        else
          run_list=
          while read line; do
            run_list="$run_list $line"
          done <<EOF
        ${{ inputs.checks }}
        EOF
        fi
        echo "run_list=$run_list" >> $GITHUB_OUTPUT

    - name: Run checks
      id: run-checks
      shell: bash
      env:
        STEAMPIPE_CLOUD_HOST: pipes.turbot.com
        STEAMPIPE_CLOUD_TOKEN: ${{ inputs.pipes-token }}
        STEAMPIPE_CHECK_DISPLAY_WIDTH: 120
        STEAMPIPE_DISPLAY_WIDTH: 120
      run: |
        set +e
        control_output="--output=brief"
        control_exports="--export=check-output.json --export=check-output.md --export=check-output.csv"
        if [[ "${{ inputs.additional-args }}" == *"--output"* ]]; then
          control_output=""
        fi

        additional_args=$(echo "${{ inputs.additional-args }}" | sed -e "s/--share//g" | sed -e "s/--snapshot//g")

        snapshot_type=""
        snapshot_tags="--snapshot-tag \"repo=$GITHUB_REPO\" --snapshot-tag \"run_id=$GITHUB_RUN_ID\" --snapshot-tag \"workflow=$GITHUB_WORKFLOW_REF\""
        if [ "${{ inputs.snapshot-type }}" == "public" ];then
          snapshot_type="--share $snapshot_tags"
        elif [ "${{ inputs.snapshot-type }}" == "private" ];then
          snapshot_type="--snapshot $snapshot_tags"
        elif [[ -n "${{ inputs.snapshot-type }}" ]];then
          echo "Error: invalid value for input 'snapshot-type' provided: ${{ inputs.snapshot-type }} - valid values are 'public' and 'private'"
          exit 3
        fi

        steampipe check ${{ steps.get-checks.outputs.run_list }} $control_output $control_exports --mod-location=${{ steps.make-temp-dir.outputs.tmp-mod-dir }} $snapshot_type $additional_args | tee /tmp/output.log
        exit_code=$?

        snapshot_url=$(cat /tmp/output.log | grep "Snapshot uploaded" | sed -e "s/^Snapshot uploaded to //")
        if [ -n "$snapshot_url" ];then
          echo "> Turbot Pipes Snapshot" >> $GITHUB_STEP_SUMMARY
          echo "> ${{ inputs.snapshot-type }} snapshot: $snapshot_url" >> $GITHUB_STEP_SUMMARY
        fi
        echo "$(cat check-output.md)" >> $GITHUB_STEP_SUMMARY
        # 0 ok, 1 alarms, 2 errors, these should exit ok - other codes should exit out with error code
        if [[ $exit_code -le 2 ]];then
          exit 0
        else
          exit $exit_code
        fi

    - name: Upload Artifacts
      id: upload-artifacts
      continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: exported-results
        path: |
          ./*.md
          ./*.json
          ./*.csv
          !./package*.json
          !./README.md

    - name: Setup Node
      if: inputs.create-annotations == 'true'
      uses: actions/setup-node@v3

    - name: Annotate and summarize
      if: inputs.create-annotations == 'true'
      shell: bash
      run: |
        node ${{ github.action_path }}/dist/index.js ${{ steps.get-checks.outputs.run_list }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
