name: Run Steampipe Terraform Compliance
on:
  # push:
  #   branches:
  #     - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use local my-action
        uses: ./
        with:
          version: latest
          connection_config: |
            connection "terraform" {
              plugin = "terraform"
              paths = ["examples/terraform/aws/**/*.tf"] # Provide the path to terraform files
            }
          plugins: terraform
          mod: 'https://github.com/turbot/steampipe-mod-terraform-aws-compliance.git'
          export: json
          run: control.ec2_ebs_default_encryption_enabled ## You can provide multiple controls or benchmarks separated by comma
          output: text
