name: Run Steampipe Terraform Compliance
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  steampipe-terraform-compliance:
    strategy:
      matrix:
        include:
          - cloud: "aws"
            search_path: "aws_tf"
          - cloud: "azure"
            search_path: "azure_tf"
          - cloud: "gcp"
            search_path: "gcp_tf"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Steampipe
        uses: turbot/steampipe-action-setup@v1.4.0
        with:
          plugin-connections: |
            connection "aws_tf" {
              plugin = "terraform"
              paths  = ["examples/terraform/aws/**/*.tf"]
            }

            connection "gcp_tf" {
              plugin = "terraform"
              paths  = ["examples/terraform/gcp/**/*.tf"]
            }

            connection "azure_tf" {
              plugin = "terraform"
              paths  = ["examples/terraform/azure/**/*.tf"]
            }

      - name: Run Steampipe Terraform Compliance - ${{ matrix.cloud }}
        uses: turbot/steampipe-action-check
        with:
          mod-url: 'https://github.com/turbot/steampipe-mod-terraform-${{ matrix.cloud }}-compliance'
          additional-args: '--search-path-prefix=${{ matrix.search_path }}'
