name: Check dist
on:
  push:
    branches:
      - main
    paths:
      - src/*
  pull_request:
    paths:
      - src/*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      - name: Install Deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Comparison
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff
      - name: Upload Artifacts
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: dist
          path: dist/