name: Test Steampipe Check action
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Steampipe and install plugins
        id: setup-steampipe
        uses: turbot/steampipe-action-setup@48bd85e67fddae9843fe2ad7ef6af96a332507c5 # v1
        with:
          plugin-connections: |
            connection "aws_tf" {
              plugin = "terraform"
              configuration_file_paths = [ "./tests/terraform/aws/**/*.tf" ]
            }

      - name: Run Terraform checks
        uses: ./
        with:
          mod-url: https://github.com/turbot/steampipe-mod-terraform-aws-compliance
          additional-args: --output=none # Added to reduce stdout when running tests
