name: Run Steampipe awstf compliance
on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  steampipe-awstf-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup steampipe
        id: setup-steampipe
        uses: turbot/steampipe-action-setup@v1.4.0
        with:
          plugin-connections: |
            connection "aws_tf" {
              plugin = "terraform"
              paths  = [ "./test-files/terraform/aws/**/*.tf" ]
            }
      - name: Steampipe AWS TF scan action
        uses: ./
        with:
          mod-url: https://github.com/turbot/steampipe-mod-terraform-aws-compliance
          additional-args: --output=none